### PR TITLE
Improvements to CMake documentation generation

### PR DESCRIPTION
**Pull request by UniqMartin**
The details are all in the commit messages or commits themselves. Note that this only addresses the build system for the CMake documentation, not the documentation inside the CMake files.

Among the improvements:
* Many refinements in the `Rakefile` (new targets, better checks, more features)
* Fixed or updated URLs
* CSS file referenced relative to HTML files to be independent of a fixed hosting location
* Adjusted spacing and alignment of the menus

The commits do not contain a rebuilt documentation. Feel free to do that after the merge in a separate commit, if happy with my changes. For an up-to-date documentation with the changes from this pull request, see <http://uniqmartin.github.io/texworks/> (files in [my `gh-pages` branch](https://github.com/UniqMartin/texworks/tree/gh-pages)).

### CODE REVIEW

**Comment by UniqMartin** [comment]
Thanks for the detailed feedback! I believe I addressed all issues in my comments and/or in the new commits.

**Comment by UniqMartin** [comment]
Is there anything I can do to move this issue forward?

**Comment by UniqMartin** [comment]
Closing for now due to lack of feedback and upstream activity. Hopefully I can reopen some day …

**Comment by stloeffler** [comment]
Sorry for the long delay - I've been very busy with non-Tw things for the past half year...
Thanks a lot for your work!

**Comment by UniqMartin** [comment]
Thanks for merging. I'm very glad you're back!

**Pull request merged**
